version: '3.1'

services:
  postgresql-primary:
    image: bitnami/postgresql:latest
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres_password
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
    volumes:
      - postgresql_data:/bitnami/postgresql

  postgresql-replica1:
    image: bitnami/postgresql:latest
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres_password
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_MASTER_HOST=postgresql-primary

  postgresql-replica2:
    image: bitnami/postgresql:latest
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres_password
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_MASTER_HOST=postgresql-primary

  postgresql-replica3:
    image: bitnami/postgresql:latest
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres_password
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_MASTER_HOST=postgresql-primary

  postgresql-replica4:
    image: bitnami/postgresql:latest
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres_password
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_MASTER_HOST=postgresql-primary

  postgresql-replica5:
    image: bitnami/postgresql:latest
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres_password
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_MASTER_HOST=postgresql-primary

volumes:
  postgresql_data:
    driver: local
